# Generated by Django 2.2.5 on 2020-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_redirectdummypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectdummypage',
            name='redirect_to',
            field=models.URLField(blank=True, null=True),
        ),
    ]
