# Generated by Django 2.2.5 on 2020-02-13 14:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200213_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='header_image',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(help_text='An image as a banner for the page', required=False)), ('insert_html', wagtail.core.blocks.RawHTMLBlock(help_text='Try a free fontawesome icon. https://fontawesome.com/icons?d=gallery&m=free', required=False))], blank=True),
        ),
    ]
