# Generated by Django 2.2.5 on 2020-02-14 07:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0011_detailpage_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpage',
            name='header_image',
        ),
        migrations.AddField(
            model_name='detailpage',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='short_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A one line description of the page that will appear in overview page.', null=True),
        ),
    ]
