# Generated by Django 2.2.5 on 2020-02-19 11:04

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_customimage_customrendition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customimage',
            name='license',
            field=models.CharField(blank=True, choices=[('https://creativecommons.org/licenses/by/4.0/', 'CC BY 4.0'), ('https://creativecommons.org/licenses/by-sa/4.0/', 'CC BY-SA 4.0'), ('https://creativecommons.org/licenses/by-nd/4.0/', 'CC BY-ND 4.0'), ('https://creativecommons.org/licenses/by-nc/4.0/', 'CC BY-NC 4.0'), ('https://creativecommons.org/licenses/by-nc-sa/4.0/', 'CC BY-NC-SA 4.0'), ('https://creativecommons.org/licenses/by-nc-nd/4.0/', 'CC BY-NC-ND 4.0'), ('https://creativecommons.org/publicdomain/zero/1.0/', 'CC0 1.0')], default='https://creativecommons.org/licenses/by/4.0/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customimage',
            name='title',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
