# Generated by Django 2.2.5 on 2020-02-19 11:53

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200219_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='caption',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customimage',
            name='title',
            field=models.CharField(default=None, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
