# Generated by Django 2.2.5 on 2020-02-24 10:13

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200220_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='caption',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Description of the image. Image attribution will be generated in the form of "{caption}" by {owner} licensed under {license}.', null=True),
        ),
    ]
