# Generated by Django 2.2.5 on 2020-03-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200226_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overviewpage',
            name='subtitle',
        ),
    ]
