# Generated by Django 2.2.5 on 2020-03-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_overviewpage_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('overviewpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.OverviewPage')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.overviewpage',),
        ),
    ]
