# Generated by Django 2.2.5 on 2020-03-04 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('home', '0022_landingpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandingPage',
            new_name='AppLandingPage',
        ),
        migrations.CreateModel(
            name='LinkedButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The text to be displayed on the button.', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='The html code of the icon to be displayed on the button, e.g. \'<i class="fab fa-mdb"></i>\', Fontawesome icons available: https://bit.ly/2wYnKyD', max_length=100, null=True)),
                ('color', models.CharField(blank=True, help_text="Button class e.g.'btn btn-primary'. Button classes available (free version only): https://bit.ly/3ctJtir", max_length=100, null=True)),
                ('linked_page', models.ForeignKey(blank=True, help_text='The page which this button directs the users to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_button', to='wagtailcore.Page')),
            ],
            options={
                'unique_together': {('linked_page', 'text', 'color')},
            },
        ),
        migrations.CreateModel(
            name='LinkButtonOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.LinkedButton')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_buttons', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
