# Generated by Django 2.2.5 on 2020-03-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200304_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='cardtag',
            name='tag',
        ),
        migrations.AlterModelOptions(
            name='detailpage',
            options={'ordering': ['-last_published_at']},
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardTag',
        ),
    ]
