# Generated by Django 2.2.5 on 2020-03-05 09:21

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200304_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectdummypage',
            name='body',
            field=wagtail.core.fields.StreamField([('insert_html', wagtail.core.blocks.RawHTMLBlock(help_text='This is a standard HTML block. Anything written in HTML here will be rendered in a DIV element', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], blank=True),
        ),
        migrations.AlterField(
            model_name='linkedbutton',
            name='color',
            field=models.CharField(blank=True, help_text="Button class e.g. 'btn-primary'. Button classes available (free version only): https://bit.ly/3ctJtir", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='linkedbutton',
            name='icon',
            field=models.CharField(blank=True, help_text="The html code of the icon to be displayed on the button, e.g. 'fas fa-arrow-left', Fontawesome icons available: https://bit.ly/2wYnKyD", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='body',
            field=wagtail.core.fields.StreamField([('insert_html', wagtail.core.blocks.RawHTMLBlock(help_text='This is a standard HTML block. Anything written in HTML here will be rendered in a DIV element', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], blank=True),
        ),
    ]
