# Generated by Django 2.2.5 on 2020-03-06 13:02

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200306_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_page', wagtail.core.fields.StreamField([('footer_pages', wagtail.core.blocks.PageChooserBlock(help_text='Select page to render in footer', required=False))], blank=True, null=True)),
                ('logo', wagtail.core.fields.StreamField([('logos', wagtail.core.blocks.StructBlock([('logo_image', wagtail.images.blocks.ImageChooserBlock(help_text='Select a logo.', required=False)), ('logo_url', wagtail.core.blocks.URLBlock(help_text='Set a url which the logo refers to.', required=False))]))], blank=True, null=True)),
                ('text', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'underline', 'link', 'superscript', 'subscript'], help_text='A short line of text to be displayed at the bottom of footer.', required=False))], blank=True, null=True)),
            ],
        ),
    ]
