# Generated by Django 2.2.5 on 2020-03-17 07:18

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20200316_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewpage',
            name='pin',
            field=wagtail.core.fields.StreamField([('pinned_pages', wagtail.core.blocks.PageChooserBlock(help_text='Select page to be pinned in this page', required=False))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailpage',
            name='show_in_parent',
            field=models.BooleanField(blank=True, default=False, help_text='If true, this page will appear in the parent page if parent page type is AppLandingPage or OverviewPage.', null=True),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='show_in_parent',
            field=models.BooleanField(blank=True, default=False, help_text='If true, this page will appear in the parent page if parent page type is AppLandingPage or OverviewPage.', null=True),
        ),
        migrations.AlterField(
            model_name='redirectdummypage',
            name='show_in_parent',
            field=models.BooleanField(blank=True, default=False, help_text='If true, this page will appear in the parent page if parent page type is AppLandingPage or OverviewPage.', null=True),
        ),
    ]
