# Generated by Django 2.2.5 on 2020-03-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20200317_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applandingpage',
            options={'ordering': ['-last_published_at']},
        ),
        migrations.AlterModelOptions(
            name='overviewpage',
            options={'ordering': ['-last_published_at']},
        ),
        migrations.AlterModelOptions(
            name='redirectdummypage',
            options={'ordering': ['-last_published_at']},
        ),
    ]
