# Generated by Django 2.2.5 on 2020-04-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_linkpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='license',
            field=models.CharField(blank=True, choices=[('https://creativecommons.org/licenses/by/3.0/', 'CC BY 3.0'), ('https://creativecommons.org/licenses/by/4.0/', 'CC BY 4.0'), ('https://creativecommons.org/licenses/by-sa/4.0/', 'CC BY-SA 4.0'), ('https://creativecommons.org/licenses/by-nd/4.0/', 'CC BY-ND 4.0'), ('https://creativecommons.org/licenses/by-nc/4.0/', 'CC BY-NC 4.0'), ('https://creativecommons.org/licenses/by-nc-sa/4.0/', 'CC BY-NC-SA 4.0'), ('https://creativecommons.org/licenses/by-nc-nd/4.0/', 'CC BY-NC-ND 4.0'), ('https://creativecommons.org/publicdomain/zero/1.0/', 'CC0 1.0')], default='https://creativecommons.org/licenses/by/4.0/', help_text='Please select a license.', max_length=200, null=True),
        ),
    ]
