# Generated by Django 2.2.12 on 2020-04-27 05:16

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20200420_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='body',
            field=wagtail.core.fields.StreamField([('insert_html', wagtail.core.blocks.RawHTMLBlock(help_text='This is a standard HTML block. Anything written in HTML here will be rendered in a DIV element', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False, template='home/table_block.html'))], blank=True),
        ),
        migrations.AlterField(
            model_name='overviewpage',
            name='body',
            field=wagtail.core.fields.StreamField([('insert_html', wagtail.core.blocks.RawHTMLBlock(help_text='This is a standard HTML block. Anything written in HTML here will be rendered in a DIV element', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False, template='home/table_block.html'))], blank=True),
        ),
        migrations.AlterField(
            model_name='redirectdummypage',
            name='body',
            field=wagtail.core.fields.StreamField([('insert_html', wagtail.core.blocks.RawHTMLBlock(help_text='This is a standard HTML block. Anything written in HTML here will be rendered in a DIV element', required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('table', wagtail.contrib.table_block.blocks.TableBlock(required=False, template='home/table_block.html'))], blank=True),
        ),
    ]
