# Generated by Django 2.2.12 on 2020-07-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20200430_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailindexpage',
            name='application',
            field=models.CharField(choices=[('home', 'General pages for biodiversity.aq'), ('polaaar', 'POLA3R')], default='home', help_text='The application which this page should belongs to.', max_length=200),
        ),
        migrations.AddField(
            model_name='detailpage',
            name='application',
            field=models.CharField(choices=[('home', 'General pages for biodiversity.aq'), ('polaaar', 'POLA3R')], default='home', help_text='The application which this page should belongs to.', max_length=200),
        ),
        migrations.AddField(
            model_name='overviewpage',
            name='application',
            field=models.CharField(choices=[('home', 'General pages for biodiversity.aq'), ('polaaar', 'POLA3R')], default='home', help_text='The application which this page should belongs to.', max_length=200),
        ),
        migrations.AddField(
            model_name='redirectdummypage',
            name='application',
            field=models.CharField(choices=[('home', 'General pages for biodiversity.aq'), ('polaaar', 'POLA3R')], default='home', help_text='The application which this page should belongs to.', max_length=200),
        ),
    ]
