# Generated by Django 2.2.14 on 2020-08-10 06:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('home', '0038_auto_20200709_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('repeat_in_subnav', models.BooleanField(default=False, help_text="If checked, a link to this page will be repeated alongside it's direct children when displaying a sub-navigation for this page.", verbose_name='repeat in sub-navigation')),
                ('repeated_item_text', models.CharField(blank=True, help_text="e.g. 'Section home' or 'Overview'. If left blank, the page title will be used.", max_length=255, verbose_name='repeated item link text')),
                ('application', models.CharField(choices=[('home', 'General pages for biodiversity.aq'), ('polaaar', 'POLA3R')], default='home', help_text='The application which this page should belongs to.', max_length=200)),
                ('colour_theme', models.CharField(blank=True, choices=[('#0099CC', 'Default blue'), ('#3952a4', 'Dark blue'), ('#003a4e', 'Dark green'), ('#006f71', 'Teal'), ('#ec6633', 'Orange'), ('#d51e47', 'Red')], default='#0099CC', help_text='Please select a colour theme for the header and footer.', max_length=200, null=True)),
                ('short_description', wagtail.core.fields.RichTextField(blank=True, help_text='A one line description of the page to help user discover this page.', null=True)),
                ('html_page_path', models.CharField(default='', help_text='relative path from the static directory to the html file to be loaded', max_length=500)),
                ('show_in_recent', models.BooleanField(blank=True, default=False, help_text='If true, this page will appear in the "Recent" section of its parent if it is an AppLandingPage order by last published date', null=True)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
