# Generated by Django 2.2.20 on 2021-06-25 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_repopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='displayed_publish_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 6, 25), help_text='Will be displayed at the end of the page.', null=True),
        ),
        migrations.AddField(
            model_name='overviewpage',
            name='displayed_publish_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 6, 25), help_text='Will be displayed at the end of the page.', null=True),
        ),
        migrations.AddField(
            model_name='redirectdummypage',
            name='displayed_publish_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 6, 25), help_text='Will be displayed at the end of the page.', null=True),
        ),
    ]
