# Generated by Django 2.2.5 on 2019-11-07 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import spirit.core.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='fullname')),
                ('slug', spirit.core.utils.models.AutoSlugField(allow_unicode=True, blank=True, db_index=False, populate_from='user.username')),
                ('nickname', models.CharField(max_length=255, verbose_name='nickname')),
                ('location', models.CharField(blank=True, max_length=75, null=True, verbose_name='location')),
                ('last_seen', models.DateTimeField(auto_now=True, null=True, verbose_name='last seen')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last ip')),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=32, null=True, verbose_name='time zone')),
                ('is_administrator', models.BooleanField(default=False, verbose_name='administrator status')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='moderator status')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified his account by email or by other means. Un-select this to let the user activate his account.', verbose_name='verified')),
                ('topic_count', models.PositiveIntegerField(default=0, verbose_name='topic count')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='comment count')),
                ('last_post_hash', models.CharField(blank=True, max_length=32, null=True, verbose_name='last post hash')),
                ('last_post_on', models.DateTimeField(blank=True, null=True, verbose_name='last post on')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('resident_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('home_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('introduction', models.TextField(blank=True, max_length=1500, null=True)),
                ('gdpr', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('email_contact', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='st', to=settings.AUTH_USER_MODEL, verbose_name='profile')),
            ],
            options={
                'verbose_name': 'forum profile',
                'verbose_name_plural': 'forum profiles',
            },
        ),
    ]
