# Generated by Django 2.2.5 on 2019-12-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentevent',
            options={'ordering': ['parent_event_name']},
        ),
        migrations.RenameField(
            model_name='parentevent',
            old_name='event_name',
            new_name='parent_event_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='resource_relationship',
        ),
    ]
