# Generated by Django 2.2.5 on 2019-12-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0002_auto_20191219_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequences',
            name='seqData_numberOfSequences',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
