# Generated by Django 2.2.5 on 2019-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0003_sequences_seqdata_numberofsequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='Latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='environment',
            name='Longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
