# Generated by Django 2.2.5 on 2019-12-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0003_sequences_seqdata_numberofsequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='html_tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
