# Generated by Django 2.2.5 on 2019-12-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0005_auto_20191222_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='env_method',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='env_numeric_value',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='env_text_value',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='env_units',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='env_variable',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='sequences',
        ),
    ]
