# Generated by Django 2.2.5 on 2019-12-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0005_auto_20191223_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmetadata',
            old_name='geom',
            new_name='geomet',
        ),
    ]
