# Generated by Django 2.2.5 on 2020-03-04 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polaaar', '0006_auto_20191223_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geog_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('geog_level', models.CharField(choices=[('Conti', 'Continent'), ('Count', 'Country'), ('Sta', 'State'), ('Prov', 'Province'), ('IslG', 'Island_Group'), ('Isl', 'Island'), ('Pla', 'Place_Name'), ('Ocean', 'Ocean'), ('Sea', 'Sea'), ('Bay', 'Bay'), ('Wb', 'Water_body')], max_length=300)),
                ('parent_geog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='GeogName', to='polaaar.Geog_Location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='ParentEvent',
            new_name='EventHierarchy',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='additional_info',
            new_name='additional_information',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='location',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='authors_list',
            new_name='full_reference',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='Longitude',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='island',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='islandGroup',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='waterBody',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='occurrences',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='short_authors',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='env_biome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='projectmetadata',
            name='associated_references',
        ),
        migrations.AddField(
            model_name='projectmetadata',
            name='associated_references',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polaaar.Reference'),
        ),
        migrations.DeleteModel(
            name='Biome',
        ),
        migrations.AddField(
            model_name='metadata',
            name='geographic_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polaaar.Geog_Location'),
        ),
    ]
