# Generated by Django 2.2.5 on 2019-12-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0006_auto_20191222_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='env_variable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='polaaar.Variable'),
            preserve_default=False,
        ),
    ]
