# Generated by Django 2.2.5 on 2019-12-22 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0007_environment_env_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='env_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polaaar.sampling_method'),
        ),
    ]
