# Generated by Django 2.2.5 on 2019-12-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0008_environment_env_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='env_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polaaar.units'),
        ),
    ]
