# Generated by Django 2.2.5 on 2020-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0009_mailfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventhierarchy',
            old_name='project',
            new_name='project_metadata',
        ),
        migrations.RemoveField(
            model_name='event',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='mailfile',
            name='document',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
