# Generated by Django 2.2.5 on 2019-12-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0009_environment_env_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='sequences',
            field=models.ManyToManyField(blank=True, to='polaaar.Sequences'),
        ),
    ]
