# Generated by Django 2.2.5 on 2019-12-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0010_environment_sequences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='sequence',
        ),
    ]
