# Generated by Django 2.2.5 on 2020-03-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0010_auto_20200314_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhierarchy',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventtype', to='polaaar.EventType'),
        ),
    ]
