# Generated by Django 2.2.5 on 2020-03-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0011_auto_20200320_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmetadata',
            name='associated_references',
        ),
        migrations.AddField(
            model_name='projectmetadata',
            name='associated_references',
            field=models.ManyToManyField(blank=True, to='polaaar.Reference'),
        ),
    ]
