# Generated by Django 2.2.5 on 2020-03-21 15:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polaaar', '0013_event_event_metadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metadata',
            new_name='SampleMetadata',
        ),
    ]
