# Generated by Django 2.2.5 on 2020-03-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0014_auto_20200321_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhierarchy',
            name='project_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_hierarchy', to='polaaar.ProjectMetadata'),
        ),
    ]
