# Generated by Django 2.2.5 on 2020-03-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0015_auto_20200322_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='parent_sample',
        ),
        migrations.AddField(
            model_name='event',
            name='event_hierarchy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='polaaar.EventHierarchy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polaaar.Event'),
        ),
    ]
