# Generated by Django 2.2.5 on 2020-03-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0016_auto_20200322_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventhierarchy',
            options={'ordering': ['event_hierarchy_name']},
        ),
        migrations.RenameField(
            model_name='eventhierarchy',
            old_name='parent_event_name',
            new_name='event_hierarchy_name',
        ),
        migrations.RenameField(
            model_name='eventhierarchy',
            old_name='parent_event',
            new_name='parent_event_hierarchy',
        ),
    ]
