# Generated by Django 2.2.5 on 2020-03-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0017_auto_20200322_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequences',
            name='ASV_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
