# Generated by Django 2.2.5 on 2020-03-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0018_sequences_asv_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sequences_exists',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geog_location',
            name='geog_level',
            field=models.CharField(choices=[('continent', 'continent'), ('waterBody', 'waterBody'), ('country', 'country'), ('islandGroup', 'islandGroup'), ('island', 'island'), ('stateProvince', 'stateProvince'), ('county', 'county'), ('municipality', 'municipality'), ('locality', 'locality')], max_length=300),
        ),
    ]
