# Generated by Django 2.2.5 on 2020-03-24 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0019_auto_20200324_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='sequences',
        ),
        migrations.RemoveField(
            model_name='event',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='event',
            name='occurrence',
        ),
        migrations.RemoveField(
            model_name='projectmetadata',
            name='associated_references',
        ),
        migrations.RemoveField(
            model_name='samplemetadata',
            name='sequence',
        ),
        migrations.AddField(
            model_name='environment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='environment', to='polaaar.Event'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='occurrence', to='polaaar.Event'),
        ),
        migrations.AddField(
            model_name='reference',
            name='associated_projects',
            field=models.ManyToManyField(blank=True, related_name='associated_references', to='polaaar.ProjectMetadata'),
        ),
        migrations.AddField(
            model_name='sequences',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polaaar.Environment'),
        ),
        migrations.AddField(
            model_name='sequences',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polaaar.Event'),
        ),
        migrations.AlterField(
            model_name='homelessfiles',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polaaar.Event'),
        ),
    ]
