# Generated by Django 2.2.5 on 2020-03-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0021_auto_20200325_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmetadata',
            name='amplicon_image',
            field=models.ImageField(blank=True, null=True, upload_to='amplicons'),
        ),
    ]
