# Generated by Django 2.2.5 on 2020-03-25 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0022_projectmetadata_amplicon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequences',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sequences', to='polaaar.Event'),
        ),
    ]
