# Generated by Django 2.2.5 on 2020-03-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0023_auto_20200325_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homelessfiles',
            name='event',
        ),
        migrations.AddField(
            model_name='homelessfiles',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polaaar.ProjectMetadata'),
        ),
    ]
