# Generated by Django 2.2.5 on 2020-03-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0024_auto_20200326_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-collection_year', '-collection_month', '-collection_day', '-collection_time']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='collection_date',
        ),
        migrations.AddField(
            model_name='event',
            name='collection_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='collection_month',
            field=models.IntegerField(blank=True, choices=[('JAN', '01'), ('FEB', '02'), ('MAR', '03'), ('APR', '04'), ('MAY', '05'), ('JUN', '06'), ('JUL', '07'), ('AUG', '08'), ('SEP', '09'), ('OCT', '10'), ('NOV', '11'), ('DEC', '12')], null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='collection_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
