# Generated by Django 2.2.5 on 2020-03-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0026_auto_20200327_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmetadata',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='project_files'),
        ),
    ]
