# Generated by Django 2.2.5 on 2020-03-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0027_auto_20200327_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_sample_metadata', to='polaaar.SampleMetadata'),
        ),
    ]
