# Generated by Django 2.2.5 on 2020-03-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0028_auto_20200328_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='occurrence', to='polaaar.Taxa'),
        ),
    ]
