# Generated by Django 2.2.5 on 2020-03-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0029_auto_20200328_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetadata',
            name='geographic_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_metadata', to='polaaar.Geog_Location'),
        ),
    ]
