# Generated by Django 2.2.5 on 2020-03-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0031_auto_20200329_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomelessFiles',
            new_name='ProjectFiles',
        ),
        migrations.RemoveField(
            model_name='projectmetadata',
            name='project_file',
        ),
        migrations.AlterField(
            model_name='event',
            name='collection_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventhierarchy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
