# Generated by Django 2.2.12 on 2020-06-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0032_auto_20200330_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmetadata',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
