# Generated by Django 2.2.12 on 2020-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0035_auto_20200617_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='env_numeric_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='mailfile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='polaaar/mail_file/'),
        ),
    ]
