# Generated by Django 2.2.14 on 2020-08-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0036_auto_20200709_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sample_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventhierarchy',
            name='event_hierarchy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectmetadata',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='metadata_tag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='sequence_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
