# Generated by Django 2.2.14 on 2020-08-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0038_projectmetadata_gbif_dataset_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmetadata',
            name='gbif_dataset_key',
        ),
        migrations.AddField(
            model_name='projectmetadata',
            name='doi',
            field=models.CharField(blank=True, help_text='DOI of a dataset', max_length=255, null=True),
        ),
    ]
