# Generated by Django 2.2.14 on 2020-08-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0039_auto_20200824_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmetadata',
            name='doi',
        ),
        migrations.AddField(
            model_name='projectmetadata',
            name='resource_url',
            field=models.TextField(blank=True, help_text='Resource link of this dataset, preferrably points to EML resource page.', null=True),
        ),
    ]
