# Generated by Django 2.2.14 on 2020-10-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0040_auto_20200824_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmetadata',
            name='project_creator',
        ),
        migrations.AddField(
            model_name='projectmetadata',
            name='project_contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
