# Generated by Django 2.2.14 on 2020-10-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0041_auto_20201001_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmetadata',
            name='amplicon_image',
        ),
    ]
