# Generated by Django 2.2.14 on 2020-10-05 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polaaar', '0042_remove_projectmetadata_amplicon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmetadata',
            name='project_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
