# Generated by Django 2.2.14 on 2020-12-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0044_auto_20201007_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetadata',
            name='env_feature',
            field=models.CharField(blank=True, help_text='Environmental feature level includes geographic environmental features. Compared to biome; feature is a descriptor of the more local environment. Examples include: harbor; cliff; or lake. EnvO (v 2013-06-14) terms can be found via the link: www.environmentontology.org/Browse-EnvO', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='env_material',
            field=models.CharField(blank=True, help_text='The environmental material level refers to the material that was displaced by the sample; or material in which a sample was embedded; prior to the sampling event. Environmental material terms are generally mass nouns. Examples include: air; soil; or water. EnvO (v 2013-06-14) terms can be found via the link: www.environmentontology.org/Browse-EnvO', max_length=150, null=True),
        ),
    ]
