# Generated by Django 2.2.14 on 2021-01-29 10:08

from django.db import migrations
import re


def remove_project_name_from_bioproject_field(apps, schema_editor):
    Sequences = apps.get_model('polaaar', 'Sequences')
    # some bioproject number ends with weird characters e.g. PRJNA512453<ca>
    partial_matched_bioproject_regex_sequences = Sequences.objects.exclude(seqData_projectNumber__isnull=True).exclude(seqData_projectNumber__regex=r'^PRJ\w+$').filter(seqData_projectNumber__regex=r'^PRJ\w+')
    for sequence in partial_matched_bioproject_regex_sequences:
        # this will only return bioproject number's pattern
        bioproject_number = re.findall(r'^PRJ\w+', sequence.seqData_projectNumber)[0]
        sequence.seqData_projectNumber = bioproject_number
        sequence.save()
    # update the rest of Sequences which has seqData_projectNumber that do not match Bioproject regex to
    # seqData_projectNumber=None
    Sequences.objects.exclude(seqData_projectNumber__regex=r'^PRJ\w+$').update(seqData_projectNumber=None)


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0047_auto_20210129_0924'),
    ]

    operations = [
        migrations.RunPython(remove_project_name_from_bioproject_field),
    ]
