# Generated by Django 2.2.14 on 2021-02-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0048_auto_20210129_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project_metadata',
            field=models.ForeignKey(blank=True, help_text='Foreign key to ProjectMetadata record', null=True, on_delete=django.db.models.deletion.CASCADE, to='polaaar.ProjectMetadata'),
        ),
    ]
