# Generated by Django 2.2.14 on 2021-02-11 09:38

from django.db import migrations


def update_event_with_project_fk(apps, schema_editor):
    Event = apps.get_model('polaaar', 'Event')
    ProjectMetadata = apps.get_model('polaaar', 'ProjectMetadata')
    for project in ProjectMetadata.objects.all().iterator():
        Event.objects.filter(event_hierarchy__project_metadata=project).update(project_metadata=project)


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0049_event_project_metadata'),
    ]

    operations = [
        migrations.RunPython(update_event_with_project_fk),
    ]
