# Generated by Django 2.2.14 on 2021-03-23 09:47

from django.db import migrations


def remove_first_fwd_slash_of_file_path(apps, schema_editor):
    """
    Remove the first '/' of the file name
    """
    ProjectFiles = apps.get_model('polaaar', 'ProjectFiles')
    for pf in ProjectFiles.objects.all():
        path = pf.files.name
        if path.split('/')[0] == '':
            pf.files = path[1:]
            pf.save()
        else:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0050_auto_20210211_0938'),
    ]

    operations = [
        migrations.RunPython(remove_first_fwd_slash_of_file_path),
    ]
