# Generated by Django 2.2.14 on 2021-03-30 09:51

from django.db import migrations


def delete_unassociated_variable_objects(apps, schema_editor):
    Variable = apps.get_model('polaaar', 'Variable')
    Variable.objects.filter(environment__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0052_auto_20210324_0840'),
    ]

    operations = [
        migrations.RunPython(delete_unassociated_variable_objects)
    ]
