# Generated by Django 2.2.19 on 2021-05-04 05:48
from django.core.management import call_command
from django.db import migrations


def create_cache_table(apps, schema_editor):
    """A migration to create cache table via migration instead of a manual `python manage.py createcachetable`."""
    call_command('createcachetable')


class Migration(migrations.Migration):

    dependencies = [
        ('polaaar', '0053_auto_20210330_0951'),
    ]

    operations = [
        migrations.RunPython(create_cache_table),
    ]
